---
slug: :mastodon_postbox_visibility
depends:
  mikutter: 4.1.0
  plugin:
    - mastodon_gtk
    - mikutter-uwm-hommage
version: '2.0'
author: shibafu528
name: 'Mastodon Postbox Visibility'
description: 'Postboxにトゥートの可視性を設定するボタンを追加します'
