---
slug: :mastodon_postbox_visibility
depends:
  mikutter: 3.9.0
  plugin:
    - mikutter-uwm-hommage
version: '1.0'
author: shibafu528
name: 'Mastodon Postbox Visibility'
description: 'Postboxにトゥートの可視性を設定するボタンを追加します'
